spring.profiles.active=local
#spring.profiles.active=postgresdb
#spring.profiles.active=supa

spring.application.name=nhd-loader

spring.database.driverClassName=org.postgresql.Driver


spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=lt
spring.liquibase.liquibase-schema=liquibase

# logging.level.com.nhd.batch.runner.BulkRunner=debug

# spring.datasource.hikari.pool-name=HikariPool-PostgreSQL
# spring.datasource.hikari.max-lifetime=600000
# spring.datasource.hikari.maximumPoolSize=20
# spring.datasource.hikari.idleTimeout=500
# spring.datasource.testWhileIdle=true
# spring.datasource.test-on-borrow=true
# spring.datasource.hikari.leakDetectionThreshold=60000
# logging.level.com.zaxxer.hikari=DEBUG

# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.sql

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL82Dialect
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.database=postgresql
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.hibernate.show-sql=true

#docker container stop nhd-loader nhd-loader-local
#docker container rm nhd-loader nhd-loader-local
#docker image rm nhd-loader
#
#mvn package -DskipTests
#docker build -t nhd-loader:latest .
#
#docker run -d -e "SB_HOST=$SB_HOST" -e "SB_PORT=$SB_PORT" -e "SB_USER=$SB_USER"  -e "SB_PWD=$SB_PWD" -p 9083:8080 --name nhd-loader nhd-loader
#docker run -d -e "SPRING_PROFILES_ACTIVE=local"  -e "SB_HOST=192.168.20.223" -p 9083:8080 --name nhd-loader-local nhd-loader
#

