spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DB:nse-prod}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PWD:postgres}


loader.ticker.scheduler.cron="0 5 */1 * * *"
# loader.dsp_ticker.scheduler.cron="0 10 16,17,18,19,20,21,22,23 * * *"
# loader.dsp_ticker.scheduler.cron="0 10 1 * * *"
loader.dsp_ticker.scheduler.cron="0 0 16 * * 1-5"
# loader.dsp_ticker.scheduler.cron="0 5 4 * * 5"
# loader.bulk_ticker.scheduler.cron="0 20 */1 * * *"
loader.bsp_ticker.scheduler.cron="* */4 * * * ?"

logging.level.com.nhd.util.http.Http=DEBUG
