spring.datasource.url=jdbc:postgresql://${LOCAL_HOST:192.168.1.230}:${LOCAL_PORT:5432}/${LOCAL_DB:prod_nse}
spring.datasource.username=${LOCAL_USERNAME:postgres}
spring.datasource.password=${LOCAL_PWD:lanesra}


loader.ticker.scheduler.cron="0 */5 * * * *"
loader.dsp_ticker.scheduler.cron="0 10 16,17,18,19,20,21,22,23 * * *"
loader.bsp_ticker.scheduler.cron="10 */4 * * * *"