spring.datasource.url=jdbc:postgresql://${LOCAL_HOST:localhost}:${LOCAL_PORT:5432}/${LOCAL_DB:nsetest}
spring.datasource.username=${LOCAL_USERNAME:postgres}
spring.datasource.password=${LOCAL_PWD:password}

loader.ticker.scheduler.cron="0 5 */1 * * *"
loader.dsp_ticker.scheduler.cron="0 10 16,17,18,19,20,21,22,23 * * *"
loader.bulk_ticker.scheduler.cron="0 20 */1 * * *"